using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ScixingTetrisCore.Interface;
namespace ScixingTetrisCore.Tools
{
    public class TetrisMinoGenerator<TTetrisMino> : ITetrisMinoGenerator where TTetrisMino : ITetrisMino, new()
    {
        protected Random rnd;
        public IEnumerator<ITetrisMino> NextQueue;
        private int _seed;
        protected TetrisMinoGenerator(int? seed = null)
        {
            rnd = seed == null ? new Random() : new Random(seed.Value);
            //NextQueue = func();
        }
        public void SetSeed(int seed)
        {
            rnd = new Random(seed);
        }
        public ITetrisMino GetNextMino()
        {
            if (NextQueue == null) return null;
            NextQueue.MoveNext();
            var res = NextQueue.Current;
            return res;
        }

        public ITetrisMino[] GetMinoList()
        {
            return new TTetrisMino().GetMinoList();
        }

        public virtual void Reset(bool refreshSeed = true)
        {
            throw new NotImplementedException();
        }
        //public abstract IEnumerator<ITetrisMino> GetNextMino();
    }

    public class Bag7Generator<TTetrisMino> : TetrisMinoGenerator<TTetrisMino> where TTetrisMino : ITetrisMino,new()
    {
        public Bag7Generator(int? seed = null): base(seed)
        {
            NextQueue = GetNextQueue();
        }
        private IEnumerator<ITetrisMino> GetNextQueue()
        {
            // 要不要来个普通的mino?
            //TetrisMino[] list = new []
            //{ 
            //    TetrisMino.I,
            //    TetrisMino.O,
            //    TetrisMino.T,
            //    TetrisMino.J,
            //    TetrisMino.L,
            //    TetrisMino.Z,
            //    TetrisMino.S,
            //};
            TTetrisMino tetrisMino = new TTetrisMino();
            
            ITetrisMino[] list = tetrisMino.GetMinoList();
            while (true)
            {
                foreach (var res in list.OrderBy(s => rnd.Next()))
                {
                    yield return res;
                    //yield return list[1];
                }
            }
        }
        public override void Reset(bool refreshSeed = true)
        {
            if (!refreshSeed)
            {

            }
            NextQueue = GetNextQueue();
        }
    }
    public class GeekGenerator<TTetrisMino> : TetrisMinoGenerator<TTetrisMino> where TTetrisMino : ITetrisMino, new()
    {
        public GeekGenerator() : base()
        {
            NextQueue = GetNextQueue();
        }
        private IEnumerator<ITetrisMino> GetNextQueue()
        {
            // 要不要来个普通的mino?
            TTetrisMino tetrisMino = new TTetrisMino();

            ITetrisMino[] list = tetrisMino.GetMinoList();
            string gg = "ZIOSLZSIZJSSZZIZZJOLSOLLSZSJSZZIZZSJZOZSZOZZOLOZJJOIZLZSSSTSOIZOZJZZOZLZZOZOSSZZSZOTLTIZSSZLTSLTIZZJOLSZSOISZLSITZOJSZZTSTZTSTLOZOOJSTTOJZTZIOZOTZOTZTTSTZZJTZJOOOSLTSOTTTOSJTZJSJTSZLIZZZTTZOOTZZLTOZSOZTILLTSSSLITTTSJISTJZZJZZLLZTLLTZTZTOLJZZOZLZOSSSLISLTJSJLSTIZTTJTTTTSIZZZOLTLZOSITSOLOTTJSOSZZTZZIZZIILOLZOIZZZSTOZOOLTTSZZZLSITITZSTJZOJILJOSTZOLOOOIJTJOOZLZOOZTSTTISSSLTTIZSLOOJTOSITIZZLIJSSLOOIITSSOZLOJTTIOLSLTJOSZSSTZSOTTSLZILZZZTIJSZZZZZOZSTZZSZJZTSSTOSSSIZSTLSJLTZSTZOJSOSSLZSJSJLSSZTTOZTZSOOTJZZSOTSZTZOJOZJZSSSZZSZTZSSZOSTSSLJIZJSZZTLJSLSZTTITZOLOZOOLOZSZLLSLZSOZZLZOZSSZSOZZJZZOSTSOSSSZSIOTTSTZTOLZSOSJSZOZLSOOISLOOLJOZJZJSZLJTSLLTOSJTZZLTZOTSZZSIZZLZSZOTZOJSOTTSSSSSLTTZOZTZLTSJLOLSJZOZTOOITLOZILSZLOZSSSJTTTZSSZZSSOZSOSLJTOJJTOJZSIOTOZOSZZJZZOSLSJOLTZTOSSOZIZZZTJSLSILOJOSOLZOLJZOZZLZISSSISSTISOILZOJSSTOOOJOJZTLTSLSJTZSSISTSTTZTOJZSSZJOOSLTJTLSSTTZSZZZOZJJJOSSSTSZSTZTZIJTIZZSSOZLTTILSSJOZZSZZTSLOOZSSTTJSSZOIZJOSOJTTLZSZZZOTSLSSJIJTTSZZZSTOTOOSZLZIZZISTSZTJOOIZJSTTZJLOISJSSZZIJSJIOJZOJSZJSLIJTZOTSZSOTLJZIJOZOISTZZSZOIJLSJZTLZSSOSITISSSOOLZSZOSTOZOZLSZOOOZSJJJSLTSISISIOOLJZSZOOZZLSZSOZSZJTZZZIZLZZJJSTSOOSOOZJZLJSTLSTSZSSOTLSOISOJSTTJSSJOSJOOJLSOTIISJJZSISSSOLTIOTJSZZLTIZLSOSZZSTOSJZTJTZJZOZJSOJZLIJSLLSZSJITOSTZTTSZIOOOOLISZTOSZZOJJLOTLOTTOJJTZZSSIJIOSZILZZTZIZOLZLZZSZZSISIJLZIOTOLOSTOZOLJZOOZSOZSJISOZTZJZTIZSTITTSOSLLTLJIZOZZSJJSZZSZLZZOSJOJLOOJOTSZOTLTZZSTOZSZZSTZOZSOISSJLTTLZLJTTLSZZSSJIJJSTSJSIZSZOZLLTSSOTJIZSOOSTZJZJSZJTJOOOTSOLLZLSOTTZJTSOJZOSZOSJLZSIOTOSZLTSILZSJZTOOOZZZJOSJTSTOZOOIOLTTSLSTTSTJOZISTZZLSOLTOZZZTTOIOSTJTTOZSZSSLJZTZOZZTZSOSOOZOLSZZOLJSTSSTOITZTLZSJJIJSTTJSZTOIOOSZSTOJJJOZLJTTTITZOZLISSSSIZTZZTILSZSZZZZSSZTLZTTTTOIJLSTZLOJZOOLZZSOZOOIOJZJZTSOLISLJISZSLLSOSSJJOOLTSZTOOOSZTTZLJTISOTZZTJTLJOZJOOTSZTSIZZZOSISSSJILLZTOOJZZSSZSZOOSSSTOZJZOZZZZSZJSOOZSOOZIZJZTSJSJTJOZOOZTJILIOZZLSSZTOLZIOZZJTSSLITJJLOLTSLLJZSOSTZZJZOOOOISSOLILOJIIIZOJOJOZSTJZTOZJSJOZIOSZSIOZTTLTLZOJOZZTJOZJTJSSJZSIJTZZITZLZJZZZSSOTOOSJIIZTZSSSJSOITLZZSLSSSOJJOTSIOSSZZOTLZSTITZTZTOTTLISIZOZJTTLJJOJSZOISZJZSLLZJSZOOZZSSJOOZLZSSSOOTSZZSZSIZSTSOTLIOSLJZOZTJSOTJSLOJJTOSJSLSLSJSZTOSOJTIOSJLZZZLJJLOJSTOOSZZJIOJSZLSSSOSSSTOZZSJZTZZZSZSLLJOSSLTITJOLZZJZLOZJJOLOZSJZSTZLSIZSOSITOLZZZLZTIJZTOIZZISIOJZZJTSSZSLOSZZZIZSJSOTTIZOOZOLSSIIJLSLIITSSILJZOSSTZLISZZZSJLSLSTZJZSOTSZOJOZTJIZOOZJJSOOOTZLOTTOOSZOOLOSSLOSSZSSTLSZISOOSZIJJZSIILOTZTOSTOZJZJSZOZTOOZOZJOSIZSOOZOJZSSZTOSTTOJZOTSJOLJSOLTLLOZZTSZZZZZTSLZZLOOOZZTTTSOSSSZTOOTIJSJTTZSJZOOLZOTJSZTZLTTSIJZTSOSSZZSOZZZZSLISSJISJJLOZZOJJTSTTZZOSIOLSZLOZOZTLZLZSTSSOTOLSZZSIOOSTJOZSLZJSOSSSOOJSZLOOZJOOOTSSLSTOZTTTJZOJSSLTSIOZZLOILJOIZSZLLZJITOSJJJZLZZOITTTSOZTZSJZSSOJZJLZZOTZITSOLLZSJSLZZZZTTZZZTOJSSIZTTLSTOTISSSZLZOZOLSTZTZZZZOITJLTSTZSIZLLJOJSLOJZOSZOZOSJJZOTZISSSTTSZOZSTJJLTOZSZZOSISSOSZZSSSZTLOZJJOZOSOSZSSOSZTSLSITLTZJOJSOOZSOJOIZIIZLTOJSLTSLOOZSLZZZZSTZZJTOTTSSISOZZOTTZSLJOZZZLSZSJISTSZTZSZZZTSISTTJZLLLZJIJLSJZSZSJLZLLOJTZTZSTTSOLLLZOJIZTTTLZTTZLZTJISOTSSSZJSLJJSSOTLSZZOTTOOLSIIOSJTJZTSSLOZOOZSOOZTOJZTJSJJJOSOLZOSLIIZOSZOTOZLOITSSTJOTJTJSSOSZJTIOSJZSTSZJLIITIZZSSZSSSSSSSOZOSLSOSSZTJZLLOLJISSOJZSZSTSIITSLTSJOZZJSLJZJLSOZOJLZTSJLSIZTJSIZIOJTSOZOLLJZJSSTSSTOTOZZTLJSTZZZZZJZTTTSZOSOTOLZSZZTSIJJTZOZSOOSOISOSZSOOOZSZTZZZSTSTIZTLSZZTOITOSLOJZSJSJTZLSZOSZOIOOZZSTTLSLSZJZJJZSZZTZOZZZOJSTOZSZSZISTSSZSZZTIZOOTZOIOSIOLZOSZILSJOJOLZLLOLOZZJJZOSZLSZJSLSZISZJSOOSSZIJSJIZIOISLIJZLSTLOSZJZOISLTOZLJSZOJLOOJSOSTSOOOIIOOIJZLISZOZSLLSSSZSZSOZZZJTSZOZLTZSZIIZOTTSJTTSOTIJOJOIOSLSJLJSLOZSSOZSOJZIIITJTTSIISOIZLSZJIOOJLTLTZOSISLJZTLSOOOSSJZOZJZOJSJLZIZZSSOOTOZOZSTLOJSLTSZJLSZOSJSSIZSTISTSZLSOSJJSITLJLOJOZTOTSOSTTSISSIIITTSTLOSISSJJZSOTOTOIITTSZSOSLZJOJJZZZIIZZISTSSOISZZSZLOTJJSOSIOJSOZZSTZOJZTIZTIOSZZZTZOZSLLTJOSISZSZTSOZZOSOITISSSZTLTLLSSOZSSSTZTIOZTJZSZOZLTOOOJSIOZZSSSOIOSLTSLOSSOZOSOLTZIZSSJTOTSTOLSLSZZSSIZLSOTZTZLOZZSLSSJSIZZLLOZZSLZJZSLOOIOZZJZZTLTZOJITSSZSJZOTOISLZZSJSSZLZIZOTZOOSSOSSTOSTSJLSLJSOSOTZTTZTZTZSLJJILSZJOZJILZZJLZOJLJTSJISSZOLSISZSZZOTSJLJSSSOISSOILIZSZTJZOSTJTSTSJZTZLTSOTOZJOSSIOSTLZLSIIZSSLLJJOSSZLLSSOZLOOLTOZTILOOJZOZZSJSZZSSJOSTZSOLOSOTOSZSZSZSOOSSLTZOZZJLZJJOOJJOZLZITSSLZTOLSITSZTSLLZJSTOIOOSSZZSIOJZTSIOJSSZIOLTOJJJJZSSLTOJOZZTZSISZZTSZOZZSISTOTTOOTOTZOIZZSZLSJOITIOZSSIZLSJOJZZLLLSSZLLSZSLSTIZLTLLLZZZJOTZOZLTTZOJILLZJZSLITOZZSLZZISOLISOSZOSTLJLSOOOZZJTZTLZZLSJOTZZOIJTZJOLOSIIZSOSLJTJOSSTIZSJZJLTTJSISZZOOOTOLZOTSSLZZLSJOSSSJOTIZIIZZTTSJOSZLOSOZTITZSTZSZZISITJTOJLZOOITZTJOLSOSZISSSSTOOTSOZSISSSSZSOIOSTTJJJSLOZJZOLTSLLOSSIJZJZSLLOTZTIJOSSOOTSSZOJSJZIOJZLOZZOIJZLZSJIZOJTTZLTOSIOIJOZSTLJLZZIZTZZSJISIZZJSOOOLJJTZZZZZZSLJIZSTZZOOJOZSOSSTIZJTSLZSSSJSTZOIOTJZOLLZTJSOSLOZJSSOTJTZSLOSLJSZJSTOOOLOTIOTOSZLZIOSLZZZZLSZSLOSOZOSSSSLLJLLZITTSTZOOSLJSTJSSISZSZTOTOOLOZSOTLJSTTOZZOZZTOTSSSTOJOTZSSZZLTLJSLSSOTSSSZOZLSJTOOZTZZIJTOZTSSJSIOSLZJOZZSISTTILTTOSISOLSTTTOTOLLIOLSSOOTZOOOOZZJZSSSZOZJSOZZZZLLJIZOZSZTZZISLIOSJSOOSLSTOIZTOZOZOJIJZOZOZOZTISTZZLTJSZZOJSSZOOTOJOZTJLITZLTZOSZOZISJZIZJLSZIOZTOSSZZZOOTJSIOTSJTLOSOLSOLZOTLOLZZTTZJSTISZILITIJJOSZOZJTOSZLSSZSSTZOOZOTSZSSJZISSSSZIOZZTTSSLLOZJSISSOOSJTSISZTOLZJSITZOTZSZSIOJIOIZSTSZLTZZLOLSTTSSJLSOOZJJZTSJZTJZLZZLJOJZZOLZSSZZZOZZSZLJZSSLTZSSSOJIZTZSIJZOSOISZSJZLSJOLZSTSIZZOLOSIZOLLZTTZOOJTITZJJIZJTOOLZZJZZOZSZJSJSOOZLZSZTZIILSZSOJLJTSTZOTIOZTSJZOTZJOZZTSTTJZSTSTSLIZSSILSZZZZOSISOSSOTOJSSLTTIZJIOOLZTZOISOZTJSTOZOZZJZILTJOZSZSSJLZTTLSSOSOZLSIZZZLSZTJLSOJJLTSIOSTZSTTTJOJOZIOTSSZZOOZSOOJSSSOOJSOSTLZOOTOOZSZSITTZZZTTSTSZIZOZLOSSLJOSTILJOSZTSOZOZSTJSSSILOIISSJTOSTLLSZZSSOZLSZOSJSJSSTZJSTLOTZJSSSZJTLLOZOZJSJISJTLIOTOZJSSZZIIJSZJOSJOOOILZIOSLZSIZJSSZZIZZJOLSOLLSZSJSZZIZZSJZOZSZOZZOLOZJJOIZLZSSSTSOIZOZJZZOZLZZOZOSSZZSZOTLTIZSSZLTSLTIZZJOLSZSOISZLSITZOJSZZTSTZTSTLOZOOJSTTOJZTZIOZOTZOTZTTSTZZJTZJOOOSLTSOTTTOSJTZJSJTSZLIZZZTTZOOTZZLTOZSOZTILLTSSSLITTTSJISTJZZJZZLLZTLLTZTZTOLJZZOZLZOSSSLISLTJSJLSTIZTTJTTTTSIZZZOLTLZOSITSOLOTTJSOSZZTZZIZZIILOLZOIZZZSTOZOOLTTSZZZLSITITZSTJZOJILJOSTZOLOOOIJTJOOZLZOOZTSTTISSSLTTIZSLOOJTOSITIZZLIJSSLOOIITSSOZLOJTTIOLSLTJOSZSSTZSOTTSLZILZZZTIJSZZZZZOZSTZZSZJZTSSTOSSSIZSTLSJLTZSTZOJSOSSLZSJSJLSSZTTOZTZSOOTJZZSOTSZTZOJOZJZSSSZZSZTZSSZOSTSSLJIZJSZZTLJSLSZTTITZOLOZOOLOZSZLLSLZSOZZLZOZSSZSOZZJZZOSTSOSSSZSIOTTSTZTOLZSOSJSZOZLSOOISLOOLJOZJZJSZLJTSLLTOSJTZZLTZOTSZZSIZZLZSZOTZOJSOTTSSSSSLTTZOZTZLTSJLOLSJZOZTOOITLOZILSZLOZSSSJTTTZSSZZSSOZSOSLJTOJJTOJZSIOTOZOSZZJZZOSLSJOLTZTOSSOZIZZZTJSLSILOJOSOLZOLJZOZZLZISSSISSTISOILZOJSSTOOOJOJZTLTSLSJTZSSISTSTTZTOJZSSZJOOSLTJTLSSTTZSZZZOZJJJOSSSTSZSTZTZIJTIZZSSOZLTTILSSJOZZSZZTSLOOZSSTTJSSZOIZJOSOJTTLZSZZZOTSLSSJIJTTSZZZSTOTOOSZLZIZZISTSZTJOOIZJSTTZJLOISJSSZZIJSJIOJZOJSZJSLIJTZOTSZSOTLJZIJOZOISTZZSZOIJLSJZTLZSSOSITISSSOOLZSZOSTOZOZLSZOOOZSJJJSLTSISISIOOLJZSZOOZZLSZSOZSZJTZZZIZLZZJJSTSOOSOOZJZLJSTLSTSZSSOTLSOISOJSTTJSSJOSJOOJLSOTIISJJZSISSSOLTIOTJSZZLTIZLSOSZZSTOSJZTJTZJZOZJSOJZLIJSLLSZSJITOSTZTTSZIOOOOLISZTOSZZOJJLOTLOTTOJJTZZSSIJIOSZILZZTZIZOLZLZZSZZSISIJLZIOTOLOSTOZOLJZOOZSOZSJISOZTZJZTIZSTITTSOSLLTLJIZOZZSJJSZZSZLZZOSJOJLOOJOTSZOTLTZZSTOZSZZSTZOZSOISSJLTTLZLJTTLSZZSSJIJJSTSJSIZSZOZLLTSSOTJIZSOOSTZJZJSZJTJOOOTSOLLZLSOTTZJTSOJZOSZOSJLZSIOTOSZLTSILZSJZTOOOZZZJOSJTSTOZOOIOLTTSLSTTSTJOZISTZZLSOLTOZZZTTOIOSTJTTOZSZSSLJZTZOZZTZSOSOOZOLSZZOLJSTSSTOITZTLZSJJIJSTTJSZTOIOOSZSTOJJJOZLJTTTITZOZLISSSSIZTZZTILSZSZZZZSSZTLZTTTTOIJLSTZLOJZOOLZZSOZOOIOJZJZTSOLISLJISZSLLSOSSJJOOLTSZTOOOSZTTZLJTISOTZZTJTLJOZJOOTSZTSIZZZOSISSSJILLZTOOJZZSSZSZOOSSSTOZJZOZZZZSZJSOOZSOOZIZJZTSJSJTJOZOOZTJILIOZZLSSZTOLZIOZZJTSSLITJJLOLTSLLJZSOSTZZJZOOOOISSOLILOJIIIZOJOJOZSTJZTOZJSJOZIOSZSIOZTTLTLZOJOZZTJOZJTJSSJZSIJTZZITZLZJZZZSSOTOOSJIIZTZSSSJSOITLZZSLSSSOJJOTSIOSSZZOTLZSTITZTZTOTTLISIZOZJTTLJJOJSZOISZJZSLLZJSZOOZZSSJOOZLZSSSOOTSZZSZSIZSTSOTLIOSLJZOZTJSOTJSLOJJTOSJSLSLSJSZTOSOJTIOSJLZZZLJJLOJSTOOSZZJIOJSZLSSSOSSSTOZZSJZTZZZSZSLLJOSSLTITJOLZZJZLOZJJOLOZSJZSTZLSIZSOSITOLZZZLZTIJZTOIZZISIOJZZJTSSZSLOSZZZIZSJSOTTIZOOZOLSSIIJLSLIITSSILJZOSSTZLISZZZSJLSLSTZJZSOTSZOJOZTJIZOOZJJSOOOTZLOTTOOSZOOLOSSLOSSZSSTLSZISOOSZIJJZSIILOTZTOSTOZJZJSZOZTOOZOZJOSIZSOOZOJZSSZTOSTTOJZOTSJOLJSOLTLLOZZTSZZZZZTSLZZLOOOZZTTTSOSSSZTOOTIJSJTTZSJZOOLZOTJSZTZLTTSIJZTSOSSZZSOZZZZSLISSJISJJLOZZOJJTSTTZZOSIOLSZLOZOZTLZLZSTSSOTOLSZZSIOOSTJOZSLZJSOSSSOOJSZLOOZJOOOTSSLSTOZTTTJZOJSSLTSIOZZLOILJOIZSZLLZJITOSJJJZLZZOITTTSOZTZSJZSSOJZJLZZOTZITSOLLZSJSLZZZZTTZZZTOJSSIZTTLSTOTISSSZLZOZOLSTZTZZZZOITJLTSTZSIZLLJOJSLOJZOSZOZOSJJZOTZISSSTTSZOZSTJJLTOZSZZOSISSOSZZSSSZTLOZJJOZOSOSZSSOSZTSLSITLTZJOJSOOZSOJOIZIIZLTOJSLTSLOOZSLZZZZSTZZJTOTTSSISOZZOTTZSLJOZZZLSZSJISTSZTZSZZZTSISTTJZLLLZJIJLSJZSZSJLZLLOJTZTZSTTSOLLLZOJIZTTTLZTTZLZTJISOTSSSZJSLJJSSOTLSZZOTTOOLSIIOSJTJZTSSLOZOOZSOOZTOJZTJSJJJOSOLZOSLIIZOSZOTOZLOITSSTJOTJTJSSOSZJTIOSJZSTSZJLIITIZZSSZSSSSSSSOZOSLSOSSZTJZLLOLJISSOJZSZSTSIITSLTSJOZZJSLJZJLSOZOJLZTSJLSIZTJSIZIOJTSOZOLLJZJSSTSSTOTOZZTLJSTZZZZZJZTTTSZOSOTOLZSZZTSIJJTZOZSOOSOISOSZSOOOZSZTZZZSTSTIZTLSZZTOITOSLOJZSJSJTZLSZOSZOIOOZZSTTLSLSZJZJJZSZZTZOZZZOJSTOZSZSZISTSSZSZZTIZOOTZOIOSIOLZOSZILSJOJOLZLLOLOZZJJZOSZLSZJSLSZISZJSOOSSZIJSJIZIOISLIJZLSTLOSZJZOISLTOZLJSZOJLOOJSOSTSOOOIIOOIJZLISZOZSLLSSSZSZSOZZZJTSZOZLTZSZIIZOTTSJTTSOTIJOJOIOSLSJLJSLOZSSOZSOJZIIITJTTSIISOIZLSZJIOOJLTLTZOSISLJZTLSOOOSSJZOZJZOJSJLZIZZSSOOTOZOZSTLOJSLTSZJLSZOSJSSIZSTISTSZLSOSJJSITLJLOJOZTOTSOSTTSISSIIITTSTLOSISSJJZSOTOTOIITTSZSOSLZJOJJZZZIIZZISTSSOISZZSZLOTJJSOSIOJSOZZSTZOJZTIZTIOSZZZTZOZSLLTJOSISZSZTSOZZOSOITISSSZTLTLLSSOZSSSTZTIOZTJZSZOZLTOOOJSIOZZSSSOIOSLTSLOSSOZOSOLTZIZSSJTOTSTOLSLSZZSSIZLSOTZTZLOZZSLSSJSIZZLLOZZSLZJZSLOOIOZZJZZTLTZOJITSSZSJZOTOISLZZSJSSZLZIZOTZOOSSOSSTOSTSJLSLJSOSOTZTTZTZTZSLJJILSZJOZJILZZJLZOJLJTSJISSZOLSISZSZZOTSJLJSSSOISSOILIZSZTJZOSTJTSTSJZTZLTSOTOZJOSSIOSTLZLSIIZSSLLJJOSSZLLSSOZLOOLTOZTILOOJZOZZSJSZZSSJOSTZSOLOSOTOSZSZSZSOOSSLTZOZZJLZJJOOJJOZLZITSSLZTOLSITSZTSLLZJSTOIOOSSZZSIOJZTSIOJSSZIOLTOJJJJZSSLTOJOZZTZSISZZTSZOZZSISTOTTOOTOTZOIZZSZLSJOITIOZSSIZLSJOJZZLLLSSZLLSZSLSTIZLTLLLZZZJOTZOZLTTZOJILLZJZSLITOZZSLZZISOLISOSZOSTLJLSOOOZZJTZTLZZLSJOTZZOIJTZJOLOSIIZSOSLJTJOSSTIZSJZJLTTJSISZZOOOTOLZOTSSLZZLSJOSSSJOTIZIIZZTTSJOSZLOSOZTITZSTZSZZISITJTOJLZOOITZTJOLSOSZISSSSTOOTSOZSISSSSZSOIOSTTJJJSLOZJZOLTSLLOSSIJZJZSLLOTZTIJOSSOOTSSZOJSJZIOJZLOZZOIJZLZSJIZOJTTZLTOSIOIJOZSTLJLZZIZTZZSJISIZZJSOOOLJJTZZZZZZSLJIZSTZZOOJOZSOSSTIZJTSLZSSSJSTZOIOTJZOLLZ";
            foreach (var res in gg)
            {
                yield return list.First(s=>s.Name[0] == res);
            }
        }
    }
}
