using ScixingTetrisCore.AI;
using ScixingTetrisCore.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ScixingTetrisCore
{
    public class GeekTetrisAI : ITetrisAI
    {

        public TetrisTreeNode SearchTree;
        // AI自操作的版
        GeekTetrisGameBoard TetrisGameBoard = new ();
        GeekFieldEvaluator GeekFieldEvaluator = new();
        // Next表 以供查询
        private List<ITetrisMino> tetrisMinos = new List<ITetrisMino>();
        public bool IsDead => TetrisGameBoard.IsDead;

        public void AddNext(ITetrisMino[] minoTypes)
        {
            tetrisMinos.AddRange(minoTypes);
        }
        public void AddNext(ITetrisMino minoType)
        {
            tetrisMinos.Add(minoType);
        }
        TetrisAIMessage LastMessage;
        public TetrisAIMessage GetMove(int garbage = 0)
        {
            LastMessage = new TetrisAIMessage();
            LastMessage.Path.Add(TetrisMovement.Left);
            LastMessage.Path.Add(TetrisMovement.HardDrop);
            //LastMessage.TetrisMinoStatus = ;
            return LastMessage;
        }

        public void Init()
        {
            string gg = "ZIOSLZSIZJSSZZIZZJOLSOLLSZSJSZZIZZSJZOZSZOZZOLOZJJOIZLZSSSTSOIZOZJZZOZLZZOZOSSZZSZOTLTIZSSZLTSLTIZZJOLSZSOISZLSITZOJSZZTSTZTSTLOZOOJSTTOJZTZIOZOTZOTZTTSTZZJTZJOOOSLTSOTTTOSJTZJSJTSZLIZZZTTZOOTZZLTOZSOZTILLTSSSLITTTSJISTJZZJZZLLZTLLTZTZTOLJZZOZLZOSSSLISLTJSJLSTIZTTJTTTTSIZZZOLTLZOSITSOLOTTJSOSZZTZZIZZIILOLZOIZZZSTOZOOLTTSZZZLSITITZSTJZOJILJOSTZOLOOOIJTJOOZLZOOZTSTTISSSLTTIZSLOOJTOSITIZZLIJSSLOOIITSSOZLOJTTIOLSLTJOSZSSTZSOTTSLZILZZZTIJSZZZZZOZSTZZSZJZTSSTOSSSIZSTLSJLTZSTZOJSOSSLZSJSJLSSZTTOZTZSOOTJZZSOTSZTZOJOZJZSSSZZSZTZSSZOSTSSLJIZJSZZTLJSLSZTTITZOLOZOOLOZSZLLSLZSOZZLZOZSSZSOZZJZZOSTSOSSSZSIOTTSTZTOLZSOSJSZOZLSOOISLOOLJOZJZJSZLJTSLLTOSJTZZLTZOTSZZSIZZLZSZOTZOJSOTTSSSSSLTTZOZTZLTSJLOLSJZOZTOOITLOZILSZLOZSSSJTTTZSSZZSSOZSOSLJTOJJTOJZSIOTOZOSZZJZZOSLSJOLTZTOSSOZIZZZTJSLSILOJOSOLZOLJZOZZLZISSSISSTISOILZOJSSTOOOJOJZTLTSLSJTZSSISTSTTZTOJZSSZJOOSLTJTLSSTTZSZZZOZJJJOSSSTSZSTZTZIJTIZZSSOZLTTILSSJOZZSZZTSLOOZSSTTJSSZOIZJOSOJTTLZSZZZOTSLSSJIJTTSZZZSTOTOOSZLZIZZISTSZTJOOIZJSTTZJLOISJSSZZIJSJIOJZOJSZJSLIJTZOTSZSOTLJZIJOZOISTZZSZOIJLSJZTLZSSOSITISSSOOLZSZOSTOZOZLSZOOOZSJJJSLTSISISIOOLJZSZOOZZLSZSOZSZJTZZZIZLZZJJSTSOOSOOZJZLJSTLSTSZSSOTLSOISOJSTTJSSJOSJOOJLSOTIISJJZSISSSOLTIOTJSZZLTIZLSOSZZSTOSJZTJTZJZOZJSOJZLIJSLLSZSJITOSTZTTSZIOOOOLISZTOSZZOJJLOTLOTTOJJTZZSSIJIOSZILZZTZIZOLZLZZSZZSISIJLZIOTOLOSTOZOLJZOOZSOZSJISOZTZJZTIZSTITTSOSLLTLJIZOZZSJJSZZSZLZZOSJOJLOOJOTSZOTLTZZSTOZSZZSTZOZSOISSJLTTLZLJTTLSZZSSJIJJSTSJSIZSZOZLLTSSOTJIZSOOSTZJZJSZJTJOOOTSOLLZLSOTTZJTSOJZOSZOSJLZSIOTOSZLTSILZSJZTOOOZZZJOSJTSTOZOOIOLTTSLSTTSTJOZISTZZLSOLTOZZZTTOIOSTJTTOZSZSSLJZTZOZZTZSOSOOZOLSZZOLJSTSSTOITZTLZSJJIJSTTJSZTOIOOSZSTOJJJOZLJTTTITZOZLISSSSIZTZZTILSZSZZZZSSZTLZTTTTOIJLSTZLOJZOOLZZSOZOOIOJZJZTSOLISLJISZSLLSOSSJJOOLTSZTOOOSZTTZLJTISOTZZTJTLJOZJOOTSZTSIZZZOSISSSJILLZTOOJZZSSZSZOOSSSTOZJZOZZZZSZJSOOZSOOZIZJZTSJSJTJOZOOZTJILIOZZLSSZTOLZIOZZJTSSLITJJLOLTSLLJZSOSTZZJZOOOOISSOLILOJIIIZOJOJOZSTJZTOZJSJOZIOSZSIOZTTLTLZOJOZZTJOZJTJSSJZSIJTZZITZLZJZZZSSOTOOSJIIZTZSSSJSOITLZZSLSSSOJJOTSIOSSZZOTLZSTITZTZTOTTLISIZOZJTTLJJOJSZOISZJZSLLZJSZOOZZSSJOOZLZSSSOOTSZZSZSIZSTSOTLIOSLJZOZTJSOTJSLOJJTOSJSLSLSJSZTOSOJTIOSJLZZZLJJLOJSTOOSZZJIOJSZLSSSOSSSTOZZSJZTZZZSZSLLJOSSLTITJOLZZJZLOZJJOLOZSJZSTZLSIZSOSITOLZZZLZTIJZTOIZZISIOJZZJTSSZSLOSZZZIZSJSOTTIZOOZOLSSIIJLSLIITSSILJZOSSTZLISZZZSJLSLSTZJZSOTSZOJOZTJIZOOZJJSOOOTZLOTTOOSZOOLOSSLOSSZSSTLSZISOOSZIJJZSIILOTZTOSTOZJZJSZOZTOOZOZJOSIZSOOZOJZSSZTOSTTOJZOTSJOLJSOLTLLOZZTSZZZZZTSLZZLOOOZZTTTSOSSSZTOOTIJSJTTZSJZOOLZOTJSZTZLTTSIJZTSOSSZZSOZZZZSLISSJISJJLOZZOJJTSTTZZOSIOLSZLOZOZTLZLZSTSSOTOLSZZSIOOSTJOZSLZJSOSSSOOJSZLOOZJOOOTSSLSTOZTTTJZOJSSLTSIOZZLOILJOIZSZLLZJITOSJJJZLZZOITTTSOZTZSJZSSOJZJLZZOTZITSOLLZSJSLZZZZTTZZZTOJSSIZTTLSTOTISSSZLZOZOLSTZTZZZZOITJLTSTZSIZLLJOJSLOJZOSZOZOSJJZOTZISSSTTSZOZSTJJLTOZSZZOSISSOSZZSSSZTLOZJJOZOSOSZSSOSZTSLSITLTZJOJSOOZSOJOIZIIZLTOJSLTSLOOZSLZZZZSTZZJTOTTSSISOZZOTTZSLJOZZZLSZSJISTSZTZSZZZTSISTTJZLLLZJIJLSJZSZSJLZLLOJTZTZSTTSOLLLZOJIZTTTLZTTZLZTJISOTSSSZJSLJJSSOTLSZZOTTOOLSIIOSJTJZTSSLOZOOZSOOZTOJZTJSJJJOSOLZOSLIIZOSZOTOZLOITSSTJOTJTJSSOSZJTIOSJZSTSZJLIITIZZSSZSSSSSSSOZOSLSOSSZTJZLLOLJISSOJZSZSTSIITSLTSJOZZJSLJZJLSOZOJLZTSJLSIZTJSIZIOJTSOZOLLJZJSSTSSTOTOZZTLJSTZZZZZJZTTTSZOSOTOLZSZZTSIJJTZOZSOOSOISOSZSOOOZSZTZZZSTSTIZTLSZZTOITOSLOJZSJSJTZLSZOSZOIOOZZSTTLSLSZJZJJZSZZTZOZZZOJSTOZSZSZISTSSZSZZTIZOOTZOIOSIOLZOSZILSJOJOLZLLOLOZZJJZOSZLSZJSLSZISZJSOOSSZIJSJIZIOISLIJZLSTLOSZJZOISLTOZLJSZOJLOOJSOSTSOOOIIOOIJZLISZOZSLLSSSZSZSOZZZJTSZOZLTZSZIIZOTTSJTTSOTIJOJOIOSLSJLJSLOZSSOZSOJZIIITJTTSIISOIZLSZJIOOJLTLTZOSISLJZTLSOOOSSJZOZJZOJSJLZIZZSSOOTOZOZSTLOJSLTSZJLSZOSJSSIZSTISTSZLSOSJJSITLJLOJOZTOTSOSTTSISSIIITTSTLOSISSJJZSOTOTOIITTSZSOSLZJOJJZZZIIZZISTSSOISZZSZLOTJJSOSIOJSOZZSTZOJZTIZTIOSZZZTZOZSLLTJOSISZSZTSOZZOSOITISSSZTLTLLSSOZSSSTZTIOZTJZSZOZLTOOOJSIOZZSSSOIOSLTSLOSSOZOSOLTZIZSSJTOTSTOLSLSZZSSIZLSOTZTZLOZZSLSSJSIZZLLOZZSLZJZSLOOIOZZJZZTLTZOJITSSZSJZOTOISLZZSJSSZLZIZOTZOOSSOSSTOSTSJLSLJSOSOTZTTZTZTZSLJJILSZJOZJILZZJLZOJLJTSJISSZOLSISZSZZOTSJLJSSSOISSOILIZSZTJZOSTJTSTSJZTZLTSOTOZJOSSIOSTLZLSIIZSSLLJJOSSZLLSSOZLOOLTOZTILOOJZOZZSJSZZSSJOSTZSOLOSOTOSZSZSZSOOSSLTZOZZJLZJJOOJJOZLZITSSLZTOLSITSZTSLLZJSTOIOOSSZZSIOJZTSIOJSSZIOLTOJJJJZSSLTOJOZZTZSISZZTSZOZZSISTOTTOOTOTZOIZZSZLSJOITIOZSSIZLSJOJZZLLLSSZLLSZSLSTIZLTLLLZZZJOTZOZLTTZOJILLZJZSLITOZZSLZZISOLISOSZOSTLJLSOOOZZJTZTLZZLSJOTZZOIJTZJOLOSIIZSOSLJTJOSSTIZSJZJLTTJSISZZOOOTOLZOTSSLZZLSJOSSSJOTIZIIZZTTSJOSZLOSOZTITZSTZSZZISITJTOJLZOOITZTJOLSOSZISSSSTOOTSOZSISSSSZSOIOSTTJJJSLOZJZOLTSLLOSSIJZJZSLLOTZTIJOSSOOTSSZOJSJZIOJZLOZZOIJZLZSJIZOJTTZLTOSIOIJOZSTLJLZZIZTZZSJISIZZJSOOOLJJTZZZZZZSLJIZSTZZOOJOZSOSSTIZJTSLZSSSJSTZOIOTJZOLLZTJSOSLOZJSSOTJTZSLOSLJSZJSTOOOLOTIOTOSZLZIOSLZZZZLSZSLOSOZOSSSSLLJLLZITTSTZOOSLJSTJSSISZSZTOTOOLOZSOTLJSTTOZZOZZTOTSSSTOJOTZSSZZLTLJSLSSOTSSSZOZLSJTOOZTZZIJTOZTSSJSIOSLZJOZZSISTTILTTOSISOLSTTTOTOLLIOLSSOOTZOOOOZZJZSSSZOZJSOZZZZLLJIZOZSZTZZISLIOSJSOOSLSTOIZTOZOZOJIJZOZOZOZTISTZZLTJSZZOJSSZOOTOJOZTJLITZLTZOSZOZISJZIZJLSZIOZTOSSZZZOOTJSIOTSJTLOSOLSOLZOTLOLZZTTZJSTISZILITIJJOSZOZJTOSZLSSZSSTZOOZOTSZSSJZISSSSZIOZZTTSSLLOZJSISSOOSJTSISZTOLZJSITZOTZSZSIOJIOIZSTSZLTZZLOLSTTSSJLSOOZJJZTSJZTJZLZZLJOJZZOLZSSZZZOZZSZLJZSSLTZSSSOJIZTZSIJZOSOISZSJZLSJOLZSTSIZZOLOSIZOLLZTTZOOJTITZJJIZJTOOLZZJZZOZSZJSJSOOZLZSZTZIILSZSOJLJTSTZOTIOZTSJZOTZJOZZTSTTJZSTSTSLIZSSILSZZZZOSISOSSOTOJSSLTTIZJIOOLZTZOISOZTJSTOZOZZJZILTJOZSZSSJLZTTLSSOSOZLSIZZZLSZTJLSOJJLTSIOSTZSTTTJOJOZIOTSSZZOOZSOOJSSSOOJSOSTLZOOTOOZSZSITTZZZTTSTSZIZOZLOSSLJOSTILJOSZTSOZOZSTJSSSILOIISSJTOSTLLSZZSSOZLSZOSJSJSSTZJSTLOTZJSSSZJTLLOZOZJSJISJTLIOTOZJSSZZIIJSZJOSJOOOILZIOSLZSIZJSSZZIZZJOLSOLLSZSJSZZIZZSJZOZSZOZZOLOZJJOIZLZSSSTSOIZOZJZZOZLZZOZOSSZZSZOTLTIZSSZLTSLTIZZJOLSZSOISZLSITZOJSZZTSTZTSTLOZOOJSTTOJZTZIOZOTZOTZTTSTZZJTZJOOOSLTSOTTTOSJTZJSJTSZLIZZZTTZOOTZZLTOZSOZTILLTSSSLITTTSJISTJZZJZZLLZTLLTZTZTOLJZZOZLZOSSSLISLTJSJLSTIZTTJTTTTSIZZZOLTLZOSITSOLOTTJSOSZZTZZIZZIILOLZOIZZZSTOZOOLTTSZZZLSITITZSTJZOJILJOSTZOLOOOIJTJOOZLZOOZTSTTISSSLTTIZSLOOJTOSITIZZLIJSSLOOIITSSOZLOJTTIOLSLTJOSZSSTZSOTTSLZILZZZTIJSZZZZZOZSTZZSZJZTSSTOSSSIZSTLSJLTZSTZOJSOSSLZSJSJLSSZTTOZTZSOOTJZZSOTSZTZOJOZJZSSSZZSZTZSSZOSTSSLJIZJSZZTLJSLSZTTITZOLOZOOLOZSZLLSLZSOZZLZOZSSZSOZZJZZOSTSOSSSZSIOTTSTZTOLZSOSJSZOZLSOOISLOOLJOZJZJSZLJTSLLTOSJTZZLTZOTSZZSIZZLZSZOTZOJSOTTSSSSSLTTZOZTZLTSJLOLSJZOZTOOITLOZILSZLOZSSSJTTTZSSZZSSOZSOSLJTOJJTOJZSIOTOZOSZZJZZOSLSJOLTZTOSSOZIZZZTJSLSILOJOSOLZOLJZOZZLZISSSISSTISOILZOJSSTOOOJOJZTLTSLSJTZSSISTSTTZTOJZSSZJOOSLTJTLSSTTZSZZZOZJJJOSSSTSZSTZTZIJTIZZSSOZLTTILSSJOZZSZZTSLOOZSSTTJSSZOIZJOSOJTTLZSZZZOTSLSSJIJTTSZZZSTOTOOSZLZIZZISTSZTJOOIZJSTTZJLOISJSSZZIJSJIOJZOJSZJSLIJTZOTSZSOTLJZIJOZOISTZZSZOIJLSJZTLZSSOSITISSSOOLZSZOSTOZOZLSZOOOZSJJJSLTSISISIOOLJZSZOOZZLSZSOZSZJTZZZIZLZZJJSTSOOSOOZJZLJSTLSTSZSSOTLSOISOJSTTJSSJOSJOOJLSOTIISJJZSISSSOLTIOTJSZZLTIZLSOSZZSTOSJZTJTZJZOZJSOJZLIJSLLSZSJITOSTZTTSZIOOOOLISZTOSZZOJJLOTLOTTOJJTZZSSIJIOSZILZZTZIZOLZLZZSZZSISIJLZIOTOLOSTOZOLJZOOZSOZSJISOZTZJZTIZSTITTSOSLLTLJIZOZZSJJSZZSZLZZOSJOJLOOJOTSZOTLTZZSTOZSZZSTZOZSOISSJLTTLZLJTTLSZZSSJIJJSTSJSIZSZOZLLTSSOTJIZSOOSTZJZJSZJTJOOOTSOLLZLSOTTZJTSOJZOSZOSJLZSIOTOSZLTSILZSJZTOOOZZZJOSJTSTOZOOIOLTTSLSTTSTJOZISTZZLSOLTOZZZTTOIOSTJTTOZSZSSLJZTZOZZTZSOSOOZOLSZZOLJSTSSTOITZTLZSJJIJSTTJSZTOIOOSZSTOJJJOZLJTTTITZOZLISSSSIZTZZTILSZSZZZZSSZTLZTTTTOIJLSTZLOJZOOLZZSOZOOIOJZJZTSOLISLJISZSLLSOSSJJOOLTSZTOOOSZTTZLJTISOTZZTJTLJOZJOOTSZTSIZZZOSISSSJILLZTOOJZZSSZSZOOSSSTOZJZOZZZZSZJSOOZSOOZIZJZTSJSJTJOZOOZTJILIOZZLSSZTOLZIOZZJTSSLITJJLOLTSLLJZSOSTZZJZOOOOISSOLILOJIIIZOJOJOZSTJZTOZJSJOZIOSZSIOZTTLTLZOJOZZTJOZJTJSSJZSIJTZZITZLZJZZZSSOTOOSJIIZTZSSSJSOITLZZSLSSSOJJOTSIOSSZZOTLZSTITZTZTOTTLISIZOZJTTLJJOJSZOISZJZSLLZJSZOOZZSSJOOZLZSSSOOTSZZSZSIZSTSOTLIOSLJZOZTJSOTJSLOJJTOSJSLSLSJSZTOSOJTIOSJLZZZLJJLOJSTOOSZZJIOJSZLSSSOSSSTOZZSJZTZZZSZSLLJOSSLTITJOLZZJZLOZJJOLOZSJZSTZLSIZSOSITOLZZZLZTIJZTOIZZISIOJZZJTSSZSLOSZZZIZSJSOTTIZOOZOLSSIIJLSLIITSSILJZOSSTZLISZZZSJLSLSTZJZSOTSZOJOZTJIZOOZJJSOOOTZLOTTOOSZOOLOSSLOSSZSSTLSZISOOSZIJJZSIILOTZTOSTOZJZJSZOZTOOZOZJOSIZSOOZOJZSSZTOSTTOJZOTSJOLJSOLTLLOZZTSZZZZZTSLZZLOOOZZTTTSOSSSZTOOTIJSJTTZSJZOOLZOTJSZTZLTTSIJZTSOSSZZSOZZZZSLISSJISJJLOZZOJJTSTTZZOSIOLSZLOZOZTLZLZSTSSOTOLSZZSIOOSTJOZSLZJSOSSSOOJSZLOOZJOOOTSSLSTOZTTTJZOJSSLTSIOZZLOILJOIZSZLLZJITOSJJJZLZZOITTTSOZTZSJZSSOJZJLZZOTZITSOLLZSJSLZZZZTTZZZTOJSSIZTTLSTOTISSSZLZOZOLSTZTZZZZOITJLTSTZSIZLLJOJSLOJZOSZOZOSJJZOTZISSSTTSZOZSTJJLTOZSZZOSISSOSZZSSSZTLOZJJOZOSOSZSSOSZTSLSITLTZJOJSOOZSOJOIZIIZLTOJSLTSLOOZSLZZZZSTZZJTOTTSSISOZZOTTZSLJOZZZLSZSJISTSZTZSZZZTSISTTJZLLLZJIJLSJZSZSJLZLLOJTZTZSTTSOLLLZOJIZTTTLZTTZLZTJISOTSSSZJSLJJSSOTLSZZOTTOOLSIIOSJTJZTSSLOZOOZSOOZTOJZTJSJJJOSOLZOSLIIZOSZOTOZLOITSSTJOTJTJSSOSZJTIOSJZSTSZJLIITIZZSSZSSSSSSSOZOSLSOSSZTJZLLOLJISSOJZSZSTSIITSLTSJOZZJSLJZJLSOZOJLZTSJLSIZTJSIZIOJTSOZOLLJZJSSTSSTOTOZZTLJSTZZZZZJZTTTSZOSOTOLZSZZTSIJJTZOZSOOSOISOSZSOOOZSZTZZZSTSTIZTLSZZTOITOSLOJZSJSJTZLSZOSZOIOOZZSTTLSLSZJZJJZSZZTZOZZZOJSTOZSZSZISTSSZSZZTIZOOTZOIOSIOLZOSZILSJOJOLZLLOLOZZJJZOSZLSZJSLSZISZJSOOSSZIJSJIZIOISLIJZLSTLOSZJZOISLTOZLJSZOJLOOJSOSTSOOOIIOOIJZLISZOZSLLSSSZSZSOZZZJTSZOZLTZSZIIZOTTSJTTSOTIJOJOIOSLSJLJSLOZSSOZSOJZIIITJTTSIISOIZLSZJIOOJLTLTZOSISLJZTLSOOOSSJZOZJZOJSJLZIZZSSOOTOZOZSTLOJSLTSZJLSZOSJSSIZSTISTSZLSOSJJSITLJLOJOZTOTSOSTTSISSIIITTSTLOSISSJJZSOTOTOIITTSZSOSLZJOJJZZZIIZZISTSSOISZZSZLOTJJSOSIOJSOZZSTZOJZTIZTIOSZZZTZOZSLLTJOSISZSZTSOZZOSOITISSSZTLTLLSSOZSSSTZTIOZTJZSZOZLTOOOJSIOZZSSSOIOSLTSLOSSOZOSOLTZIZSSJTOTSTOLSLSZZSSIZLSOTZTZLOZZSLSSJSIZZLLOZZSLZJZSLOOIOZZJZZTLTZOJITSSZSJZOTOISLZZSJSSZLZIZOTZOOSSOSSTOSTSJLSLJSOSOTZTTZTZTZSLJJILSZJOZJILZZJLZOJLJTSJISSZOLSISZSZZOTSJLJSSSOISSOILIZSZTJZOSTJTSTSJZTZLTSOTOZJOSSIOSTLZLSIIZSSLLJJOSSZLLSSOZLOOLTOZTILOOJZOZZSJSZZSSJOSTZSOLOSOTOSZSZSZSOOSSLTZOZZJLZJJOOJJOZLZITSSLZTOLSITSZTSLLZJSTOIOOSSZZSIOJZTSIOJSSZIOLTOJJJJZSSLTOJOZZTZSISZZTSZOZZSISTOTTOOTOTZOIZZSZLSJOITIOZSSIZLSJOJZZLLLSSZLLSZSLSTIZLTLLLZZZJOTZOZLTTZOJILLZJZSLITOZZSLZZISOLISOSZOSTLJLSOOOZZJTZTLZZLSJOTZZOIJTZJOLOSIIZSOSLJTJOSSTIZSJZJLTTJSISZZOOOTOLZOTSSLZZLSJOSSSJOTIZIIZZTTSJOSZLOSOZTITZSTZSZZISITJTOJLZOOITZTJOLSOSZISSSSTOOTSOZSISSSSZSOIOSTTJJJSLOZJZOLTSLLOSSIJZJZSLLOTZTIJOSSOOTSSZOJSJZIOJZLOZZOIJZLZSJIZOJTTZLTOSIOIJOZSTLJLZZIZTZZSJISIZZJSOOOLJJTZZZZZZSLJIZSTZZOOJOZSOSSTIZJTSLZSSSJSTZOIOTJZOLLZTTTTTTTT"; // 最后的T都是补位
            for (int i = 0; i < gg.Length; ++i)
            {
                AddNext(gg[i] switch
                {
                    'Z' => GeekTetrisMino.Z,
                    'I' => GeekTetrisMino.I,
                    'O' => GeekTetrisMino.O,
                    'T' => GeekTetrisMino.T,
                    'J' => GeekTetrisMino.J,
                    'L' => GeekTetrisMino.L,
                    'S' => GeekTetrisMino.S,
                     _  => null,
                }); 
            }
        }

        public void MoveNext()
        {
            if (LastMessage == null) GetMove();
            TetrisGameBoard.TetrisMinoStatus = LastMessage.TetrisMinoStatus;
            for (int i = 0; i < LastMessage.Path.Count; ++i)
            {
                switch (LastMessage.Path[i])
                {
                    case TetrisMovement.Left:
                        TetrisGameBoard.MoveLeft();
                        break;
                    case TetrisMovement.Right:
                        TetrisGameBoard.MoveRight();
                        break;
                    case TetrisMovement.SoftDrop:
                        TetrisGameBoard.SoftDrop();
                        break;
                    case TetrisMovement.SonicDrop:
                        TetrisGameBoard.SonicDrop();
                        break;
                    case TetrisMovement.HardDrop:
                        TetrisGameBoard.HardDrop();
                        break;
                    default:
                        break;
                }
            }

            LastMessage = null;
        }

        public void ResetAI(int[] Field, ITetrisMino[] NextQueue = null)
        {
            throw new NotImplementedException();
        }

        public void SetPamras()
        {
            throw new NotImplementedException();
        }
    }
}
